feat: add docker dev support [#133]
dogecoin/dogecoin.com pull request #134
Opened 2021-03-22 08:30 UTC by nickatnight

This PR allows developers to work in an isolated container environment. Follow the Docker Guide to get started.

The container is built from a Node base image and only needs to install a single dependency, `live-server`. Running the container will boot up a local web server which is available from the host machine on `localhost:5000` or `127.0.0.1:5000`

Something to think about for the future is to modify the folder structure and move all site files to a dedicated`src` folder. Then build some minified dist bundle so files will decrease in size

2021-03-22 12:37 UTC, patricklodder commented
Thanks. Since this is a GitHub-pages repo, I think it's okay to keep the website source as the root, and instead put all support files in a subfolder (with a leading underscore so that it doesn't get published.)

Can we move the Dockerfile, and npm descriptors to `_contrib/docker`? Then you simply `docker build _contrib/docker` instead of the local dir, and I think you could omit the `ADD` as well? Also reduces image size.

2021-03-23 07:20 UTC, nickatnight commented
@patricklodder thank you for your response. Made some changes:

1. removed npm descriptor files since we need only that single dependency, and just installed `live-server` command globally.
2. moved `Dockerfile` to appropriate sub folder
3. updated docker contribution file

2021-03-23 10:14 UTC, patricklodder requested changes
One nit: there's no need to exclude node_modules anymore with the global install of live-server.

Everything else: works perfectly - thank you! 👍

2021-03-23 10:14 UTC, patricklodder commented on .gitignore
> +node_modules
I think we can remove these.

2021-03-23 17:08 UTC, nickatnight commented
@patricklodder the deed is done chief 🍻

2021-03-23 17:39 UTC, patricklodder approved these changes

2021-03-25 10:58 UTC, merged