FaH instead of Faucet
dogecoin/dogecoin.com pull request #144
Opened 2021-04-06 20:00 UTC by nformant1

Removed mining, only "mining" in "get some..." remained. Changed faucets to FoldingAtHome and added missing btn-outline-secondary.

Reason: All faucets are down.

2021-04-07 09:16 UTC, patricklodder commented
Hey! In general, I think that with all the faucets being defunct, this does offer an alternative for shibes to earn DOGE, and potentially "do good".

2 things that I noticed:

- I am not sure if FaH is "the easiest way", but maybe it's "another way"?
- Can we rename the i18n identifiers to make it reflect "FaH" and not faucets?

2021-04-07 19:15 UTC, nformant1 commented
Changed and uploaded, I also added a small OSX/python how to (link is pointing at the dogecoin rep, so its not working on my fork) - looking forward to read your feedback (:

2021-04-07 19:29 UTC, patricklodder requested changes
Thanks for the guide. Would normally ask for a separate PR but this is fine because there's not so many changes. 

There are still some minor things that still need to be resolved, then we're good.

2021-04-07 19:29 UTC, patricklodder commented on assets/i18n/en.json
> +    "dgc-exchanges-modal-dogecoinfah-desc": " - Team dogefolders.",
I think those tags are no longer implemented in the html. Can we remove them? Also for other translations.

2021-04-07 19:29 UTC, patricklodder commented on assets/i18n/doge.json
> +    "dgc-exchanges-modal-tipped": "You can get tipped Dogecoin by participating in <a class=\"btn btn-sm btn-outline-secondary\" target=\"_blank\" href=\"http://www.reddit.com/r/dogecoin\">our commun
For consistency: missed change of "the easiest" into "another".

2021-04-07 19:29 UTC, patricklodder commented on index.html
> +                        If that's not your style, the easiest way to have your first Dogecoin is to participate at Folding@Home.</span>
Does not reflect English translation.

2021-04-09 09:49 UTC, patricklodder approved these changes
This looks good to me. Reviewed the source and the result in each language.

2021-04-12 13:18 UTC, rnicoll approved these changes

2021-04-12 13:19 UTC, merged